services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: willnekker/weekly-task-list:backend
    restart: unless-stopped
    volumes:
      - ./data:/app/backend/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=willem
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    networks:
      - app-network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: willnekker/weekly-task-list:proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
